version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/stream.conf:/etc/nginx/stream.conf:ro
      - ./nginx/upstream.conf:/etc/nginx/upstream.conf:ro
      - ./nginx/security.conf:/etc/nginx/security.conf:ro
      - ./nginx/maintenance.html:/usr/share/nginx/html/maintenance.html:ro
      - ./logs:/var/log/nginx
    environment:
      - HOMELAB_IP=${HOMELAB_IP}
      - DOMAIN=${DOMAIN:-wielandtech.com}
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge

volumes:
  logs:
    driver: local
