version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx/maintenance.html:/usr/share/nginx/html/maintenance.html:ro
      - ./logs:/var/log/nginx
    environment:
      - HOMELAB_IP=${HOMELAB_IP}
      - DOMAIN=${DOMAIN:-wielandtech.com}
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge

volumes:
  logs:
    driver: local
